name: taskmanager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  objectbox: ^2.2.0
  objectbox_flutter_libs: ^2.2.0
  path_provider: ^2.1.0
  rxdart: ^0.27.7
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.4.1
  objectbox_generator: ^2.2.0

flutter:
  uses-material-design: true


objectbox:
  output_dir: data/source/generated